### ISSUE TITLE
xerces-c: update to 3.2.2

### ISSUE THREAD

**Issue by luzpaz** [funtoo/dev-kit#8]
http://apache.osuosl.org/xerces/c/3/sources/xerces-c-3.2.2.tar.gz  
Release Notes: https://issues.apache.org/jira/secure/ReleaseNote.jspa?version=12342890&styleName=Text&projectId=10510

**Comment by mrl5** [comment]
hello @luzpaz - if you'd like to report a bug kindly use https://bugs.funtoo.org/

you can also reach us on Discord - for more info check https://www.funtoo.org/Welcome
