### ISSUE TITLE
hg-git Python version

### ISSUE THREAD

**Issue by naryl** [funtoo/dev-kit#9]
`dev-vcs/hg-git` depends on mercurial  built using the same Python version. But at the moment mercurial only has 3.7, while hg-git only has 2.7. This makes hg-git unmergeable.

**Comment by mrl5** [comment]
hello @naryl - if you'd like to report a bug kindly use https://bugs.funtoo.org/

you can also reach us on Discord - for more info check https://www.funtoo.org/Welcome
